# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAJN67zmsgTccQYfmwQ328MmjsEDTqEh
"""

# importing all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading dataset
df=pd.read_csv('StudentsPerformance.csv')
df.head()

# shape of dataset(no of rows and colunms)
df.shape

# displaying colunms name
df.columns

#data-type of every colunm
df.dtypes

#count of missing value in every colunm
df.isnull().sum()

"""Since data type of every colunm is different:


*   Gender-Object/string
* race/ethnicity-Object/string
* parental level of education-Object/string
* lunch-Object/string
* test preparation course-Object/string
* math score-integer
* reading score-integer
* writing score-integer















"""

# mean,mode,median of math score colunm    problem
#print(df['math score'].mean())
print(df['math score'].mode())
print(df['math score'].median())

"""Mean of math score = 66.089
Median of math score = 66.0

> Add blockquote


"""

# mean,mode,median of reading score colunm    problem
print(df['reading score'].mean())
print(df['reading score'].mode())
print(df['reading score'].median())

"""Mean of reading score = 69.169
Median of reading score = 70.0
"""

# mean,mode,median of reading score colunm    problem
print(df['writing score'].mean())
print(df['writing score'].mode())
print(df['writing score'].median())

"""Mean of writing score = 68.054
Median of writing score = 69.0

Average/Mean of reading is greatest among all which is equal to 69.169.
"""

